account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (DashboardStatisticsView, DashBoardView, DeletePostView,
                    EditPostView, PostCreateView, StatisticsView,
                    UserAboutView, UserDeleteView, UserSettingsView)

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('statistics/<slug:username>', StatisticsView.as_view(), name='statistics'),
    path('settings/', UserSettingsView.as_view(), name='settings'),
    path('settings/<slug:username>', UserSettingsView.as_view(), name='settings'),
    path('delete/', UserDeleteView.as_view(), name='user_delete'),
    path('about/', UserAboutView.as_view(), name='about'),
    path('about/<slug:username>', UserAboutView.as_view(), name='about'),
    path('dashboard/', DashBoardView.as_view(), name='dashboard'),
    path('<slug:username>/dashboard/', DashBoardView.as_view(), name='dashboard'),
    path('dashboard/page/<int:page>/', DashBoardView.as_view(), name='dashboard'),
    path('<slug:username>/dashboard/page/<int:page>/', DashBoardView.as_view(), name='dashboard'),
    path('dashboard/delete/<slug:slug>/', DeletePostView.as_view(), name='post_delete'),
    path('<slug:username>/dashboard/delete/<slug:slug>/', 
    DeletePostView.as_view(), name='post_delete'),
    path('dashboard/edit/<slug:slug>/', EditPostView.as_view(), name='post_edit'),
    path('<slug:username>/dashboard/edit/<slug:slug>/', EditPostView.as_view(), name='post_edit'),
    path('dashboard/create/', PostCreateView.as_view(), name='post_create'),
    path('<slug:username>/dashboard/create/', PostCreateView.as_view(), name='post_create'),
    path('dashboard/statistics/', DashboardStatisticsView.as_view(), 
    name='dashboard_statistics'),
    path('<slug:username>/dashboard/statistics/', DashboardStatisticsView.as_view(), 
    name='dashboard_statistics'),
]

app/urls.py
from django.urls import path

from .views import (CategoryList, DownloadView, LikeView, PostDetail, PostList,
                    PublisherList)

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('page/<int:page>/', PostList.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDetail.as_view(), name='post_detail'),
    path('publisher/<slug:username>/', PublisherList.as_view(), name='publisher_list'),
    path('publisher/<slug:username>/page/<int:page>/', PublisherList.as_view(), 
    name='publisher_list'),
    path('category/<slug:slug>/', CategoryList.as_view(), name='category_list'),
    path('category/<slug:slug>/page/<int:page>/', CategoryList.as_view(), name='category_list'),
    path('download/<slug:slug>/', DownloadView.as_view(), name='download'),
    path('like/<slug:slug>/', LikeView.as_view(), name='like'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.static import serve as mediaserve

handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'

urlpatterns = [
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', include('social_django.urls', namespace="google_login")),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(path(f'{settings.MEDIA_URL[1:]}<path:path>',
    mediaserve, {'document_root': settings.MEDIA_ROOT}))

templates/app/partials/filters.html
{% load tool_tags %}

<!-- filter -->
<div class="d-flex flex-column flex-md-row mt-0 mt-md-4 mb-5">
    <div class="row mr-5 filter mt-4 mt-md-0">
        <p class="ml-2 text-right">{% fws "align-right" "l" "1" %} ترتیب مرتب سازی بر اساس:</p>
        <div class="dropdown">
            <button state="1" class="btn dropdown-toggle" data-toggle="dropdown">
                {% fws "arrow-up" "l" "1" %} جدیدترین
            </button>
            <div class="dropdown-menu">
                <p state="1" class="dropdown-item py-2 text-right">
                    {% fws "arrow-up" "l" "1" %} جدیدترین</p>
                <p state="2" class="dropdown-item py-2 text-right">
                    {% fws "arrow-down" "l" "1" %} قدیمی ترین</p>
            </div>
        </div>
    </div>

    <div class="row mr-5 filter mt-4 mt-md-0">
        <p class="ml-2 text-right">{% fws "align-right" "l" "1" %} مرتب سازی بر اساس:</p>
        <div class="dropdown">
            <button state="1" class="btn dropdown-toggle" data-toggle="dropdown">
                {% fws "calendar" "l" "1" %} تاریخ ایجاد
            </button>
            <div class="dropdown-menu">
                <p class="dropdown-item py-2 text-right" state="1">
                    {% fws "calendar" "l" "1" %} تاریخ ایجاد</p>
                <p class="dropdown-item py-2 text-right" state="2">
                    {% fws "eye" "l" "1" %} تعداد بازدید ها</p>
                <p class="dropdown-item py-2 text-right" state="3">
                    {% fws "heart" "l" "1" %} تعداد لایک ها</p>
                <p class="dropdown-item py-2 text-right" state="4">
                    {% fws "download" "l" "1" %} تعداد دانلود ها</p>
            </div>
        </div>
    </div>

    <div class="row p-0 m-0">
        <button class="btn text-center text-nowrap mr-5 mt-4 mt-md-0" 
        id="filter-btn">{% fws "filter" "l" "1" %} اعمال فیلتر</button>
    </div>
</div>

templates/app/partials/navbar.html
{% load category_navbar %}
{% load tool_tags %}

<nav class="my-navbar">
    <div class="container-fluid">
        <div class="row col-12 d-flex justify-content-between align-items-center">
            <!-- title -->
            <div class="title">
                <a class="navbar-link" href="{% url 'post_list' %}">
                    <h3>{% fws "image" %} عکس کده</h3>
                </a>
            </div>

            <!-- menu bar -->
            <div class="menu-bar d-flex d-xl-none">
                {% fws "bars" %}
            </div>

            <!-- upload -->
            <div class="row upload d-none d-md-block">
                {% if not request.user.is_authenticated %}
                    <a href="#" onclick="$('.login-link').click()">
                        {% fws "upload" %} آپلود عکس</a>
                {% else %}
                    <a href="{% url 'account:post_create' %}">{% fws "upload" %} آپلود عکس</a>
                {% endif %}
            </div>

            <!-- category -->
            <div class="overlay-nav"></div>
            <ul class="row list-unstyled flex-column flex-lg-row">
                <li class="d-block d-xl-none">
                    {% fws "close" %}
                </li>
                {% for c in category %}
                    <li class="link text-right">
                        <a class="navbar-link" href="{% url 'category_list' c.slug %}">
                            {{ c.title }}{% fws "image" "r" "2" %}
                        </a>
                    </li>
                {% endfor %}
                {% if other_category %}
                    <li class="other-link">
                        <span>سایر دسته بندی ها{% fws "ellipsis-v" "r" "2" "d-none, d-xl-inline" %}
                        {% fws "angle-down" "r" "2" "d-xl-none" %}</span>
                        <ul class="list-unstyled animate__animated" data-is-open="false">
                            {% for c in other_category %}
                                <li class="link text-right">
                                    <a class="navbar-link" href="{% url 'category_list' c.slug %}">
                                        {{ c.title }}{% fws "image" "r" "2" %}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
                <li class="contact-link">
                    <a href="mailto:{{ email }}" class="navbar-link">ارتباط با ما{% fws "phone" "r" "2" %}</a>
                </li>
            </ul>

            <!-- registration -->
            <div class="registration">
                {% if not request.user.is_authenticated %}
                    <a href="#" class="login-link">ورود / ثبت نام</a>
                {% else %}
                    <div class="dropdown profile" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% user_profile_image request.user %}
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a href="{% url 'account:about' %}" class="dropdown-item text-right">
                            {% fws "user" "l" "1" %} پروفایل عمومی شما</a>
                            <a class="dropdown-item text-right" href="{% url 'account:dashboard' %}">
                            {% fws "tasks" "l" "1" %} مدیریت عکس های شما</a>
                            <a class="dropdown-item text-right" href="{% url 'account:settings' %}">
                            {% fws "cog" "l" "1" %} تنظیمات حساب کاربری</a>
                            <a class="dropdown-item text-right" href="{% url 'account:statistics' %}">
                            {% fws "bar-chart" "l" "1" %} آمار حساب کاربری شما</a>
                            <a class="dropdown-item text-right" href="{% url 'account:logout' %}?next={{ request.path }}">
                            {% fws "sign-out" "l" "1" %} خروج</a>
                          </div>
                    </div>
                {% endif %}
            </div>

            <!-- search button -->
            <div class="search-btn animate__animated">
                {% fws "search" %}
            </div>
        </div>
    </div>
</nav>

templates/app/partials/pagination.html
{% load tool_tags %}
{% load pagination %}

<!-- num = 9 -->
{% if paginator.num_pages > 1 %}
    <div class="col-12 col-md-10 col-lg-8 mx-auto my-4">
        <ul class="col row flex-wrap justify-content-center paginator list-unstyled mx-auto">
            {% if page_obj.has_previous %}
                <div class="page-link_" title="اولین صفحه"><a href="{{ get_url }}page/1/{% additional_param request %}">
                {% fws "angle-double-right" %}
                </a></div>
                <div class="page-link_" title="صفحه قبل"><a 
                href="{{ get_url }}page/{{ page_obj.previous_page_number }}/{% additional_param request %}">
                {% fws "angle-right" %}
                </a></div>
            {% endif %}

            {% for page in paginator.page_range %}
                {% if current_page <= 5 %}
                    {% if page <= 9 %}
                        <div class="page-link_ {% if current_page == page %}active{% endif %}"><a 
                        href="{{ get_url }}page/{{ page }}/{% additional_param request %}">{{ page|en_nums_to_fa_nums }}</a></div>
                    {% endif %}
                {% elif current_page >= paginator.num_pages|add:"-4" %}
                    {% if page > paginator.num_pages|add:"-9" %}
                        <div class="page-link_ {% if current_page == page %}active{% endif %}"><a 
                        href="{{ get_url }}page/{{ page }}/{% additional_param request %}">{{ page|en_nums_to_fa_nums }}</a></div> 
                    {% endif %}
                {% else %}
                    {% if page >= current_page|add:"-4" and page <= current_page|add:"4" %}
                        <div class="page-link_ {% if current_page == page %}active{% endif %}"><a 
                        href="{{ get_url }}/page/{{ page }}/{% additional_param request %}">{{ page|en_nums_to_fa_nums }}</a></div> 
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <div class="page-link_" title="صفحه بعد"><a 
                href="{{ get_url }}page/{{ page_obj.next_page_number }}/{% additional_param request %}">{% fws "angle-left" %}</a></div>
                <div class="page-link_" title="آخرین صفحه"><a 
                href="{{ get_url }}page/{{ paginator.num_pages }}/{% additional_param request %}">{% fws "angle-double-left" %}</a></div>
            {% endif %}
        </ul>
    </div>
{% endif %}

templates/app/partials/public_statistics.html
{% load public_statistics_tag %}
{% load tool_tags %}

<div class="main-title">
    <div class="overlay container-fluid d-flex">
        <div class="col-12 d-flex flex-wrap align-content-around">
            {% if not request.user.is_authenticated %}
                <div class="col-12 col-md-8 wow animate__animated animate__fadeInRight" data-wow-delay="200ms"><h1 class="text-right">این سایت برای به اشتراک گذاشتن عکس های شماست!</h1></div>
                <div class="col-12 col-md-8 wow animate__animated animate__fadeInRight" data-wow-delay="400ms"><h1 class="text-right">در این سایت می توانید عکس هایی که کاربران آپلود کرده اند را دانلود کنید!</h1></div>
                <div class="col-12 col-md-8 wow animate__animated animate__fadeInRight" data-wow-delay="600ms"><h1 class="text-right">شما می توانید با ثبت نام کردن در سایت عکس آپلود کنید!</h1></div>
            {% else %}
                <div class="col-12 col-md-8 wow animate__animated animate__fadeInRight" data-wow-delay="200ms"><h1 class="text-right">{% fws "picture-o" "l" "1" %} تعداد عکس های سایت: {{ post_count|en_nums_to_fa_nums }}</h1></div>
                <div class="col-12 col-md-8 wow animate__animated animate__fadeInRight" data-wow-delay="400ms"><h1 class="text-right">{% fws "user" "l" "1" %} تعداد کاربران سایت: {{ user_count|en_nums_to_fa_nums }}</h1></div>
                <div class="col-12 col-md-8 wow animate__animated animate__fadeInRight" data-wow-delay="600ms"><h1 class="text-right">{% fws "download" "l" "1" %} تعداد دانلود های سایت: {{ downloads|en_nums_to_fa_nums }}</h1></div>
            {% endif %}
        </div>
    </div>
</div>

templates/app/partials/sidebar.html
{% load sidebar_tags %}
{% load tool_tags %}
{% load jformat %}

 <!-- sidebar -->
 <div class="col-12 col-md-10 col-lg-6 col-xl-5 my-5 mx-auto">
    <div class="col-12 row line mb-4 mx-auto"></div>

    <div class="suggestion">
        <div class="suggestion-header">
            <h4 class="text-center">{{ title }}</h4>
        </div>

        <div class="suggestion-body">
            <div class="row d-flex justify-content-center">
                {% for obj in sidebar_items %}
                    <div class="suggestion-item col-10">
                        <img class="img-fluid" src="{{ obj.img.url }}" 
                        alt="{{ obj.title }}" loading="lazy" />
                        <div class="suggestion-item-overlay d-flex flex-column align-items-center">
                            <div class="pt-4 pb-0 mb-0">
                                {% user_profile_image obj.publisher "3rem" "3rem" profile_tag="a" has_title=True profile_classes="user-profile, text-center" %}
                            </div>
                            <h5 class="text-center pt-4 px-4 mt-4">{{ obj.title }}</h5>
                            <a href="{% url 'post_detail' obj.slug %}">مشاهده این عکس</a>
                            <div class="d-flex">
                                <p class="mt-3 mx-2">{{ obj.downloads.count|en_nums_to_fa_nums }} 
                                {% fws "download" "r" "1" %}</p>
                                <p class="mx-2 mt-3">{{ obj.likes.active.count|en_nums_to_fa_nums }} 
                                {% fws "heart" "r" "1" %}
                                <p class="mx-2 mt-3">{{ obj.hits.count|en_nums_to_fa_nums }} 
                                {% fws "eye" "r" "1" %}</p>
                            </div>
                            <small class="mb-5 px-4 text-right">{% fws "clock-o" "l" "1" %} منتشر شده توسط <a class="publisher" href="{% url 'publisher_list' obj.publisher %}"><b>{{ obj.publisher.get_name_or_username }}</b></a> در تاریخ {{ obj.created|jformat:"%Y/%m/%d"|en_nums_to_fa_nums}} در ساعت {{ obj.created.time|jformat:"%H:%M:%S"|en_nums_to_fa_nums }}</small>
                        </div>
                    </div>
                {% empty %}
                    <h5 class="text-center empty">محتوایی موجود نیست ...</h5>
                {% endfor %}
            </div>
        </div>
    </div>
</div>